version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-closet-app
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: my-closet-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: my-closet-db
    environment:
      MYSQL_DATABASE: my_closet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: 